### ISSUE TITLE
Running error 

### ISSUE THREAD

**Issue by entcai** [Hoohm/CITE-seq-Count#103]
Dear Dr.Hoohm,
I installed CITE-seq Count 1.4.3 , 
`pip install CITE-seq-Count==1.4.3` It showed success installation under python3.7
but after I run the code:
`CITE-seq-Count -R1 ####_R1_001.fastq.gz -R2 ####_001.fastq.gz -t samp1e_tga_list.csv -trim 22 -cbf 1 -cbl 16 -umif 17 -umil 26 -cells 1912 -wl ##_whitelist.csv -o ~/data/scRNAdata/test1/Citecount_test`

It indicated errors like these:

> /bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
Loading whitelist
Traceback (most recent call last):
  File "/Software/CITE-Seq/bin/CITE-seq-Count", line 8, in <module>
    sys.exit(main())
  File "/Software/CITE-Seq/lib/python3.7/site-packages/cite_seq_count/__main__.py", line 249, in main
    ab_map = preprocessing.parse_tags_csv(args.tags)
  File "/Software/CITE-Seq/lib/python3.7/site-packages/cite_seq_count/preprocessing.py", line 131, in parse_tags_csv
    tags[row[0].strip()] = row[1].strip()
IndexError: list index out of range
**What I should do to debug these? I have uploaded the white list and tag list files in case if your guys want to check, 
Thank you,looking forward to hearing from you**

[G.zip](https://github.com/Hoohm/CITE-seq-Count/files/4055281/G.zip)

**Comment by entcai** [comment]
after I renew the format of tag.csv. the Error disappeared. Hope it will help others if anyone have the same error as mine
