### ISSUE TITLE
Error running CITE-seq-count for 10X fastq files.

### ISSUE THREAD

**Issue by bishwaG** [Hoohm/CITE-seq-Count#13]
I got the following error when tried running CITE-seq-count. I have no clue what does the error mean. I will appreciate your help.

Command:
```sh
CITE-seq-Count --read1 $R1 --read2 $R2 \
	--tags TAG_LIST.csv \
	--cell_barcode_first_base $CB_FIRST \
	--cell_barcode_last_base $CB_LAST \
	--umi_first_base $UMI_FIRST \
	--umi_last_base $UMI_LAST \
	--hamming-distance $HAMMING_THRESH \
	--output Result.tsv \
	--whitelist $WHITELIST \
	--first_n 100000
```

Output:
```sh
loading
100,000 reads loaded
100,000 uniques reads loaded
Traceback (most recent call last):
  File "/homes/scauser/Python/CITE-seq-Count-1.3.1/bin/CITE-seq-Count", line 11, in <module>
    load_entry_point('CITE-seq-Count==1.3.1', 'console_scripts', 'CITE-seq-Count')()
  File "build/bdist.linux-x86_64/egg/cite_seq_count/__main__.py", line 284, in main
  File "build/bdist.linux-x86_64/egg/regex.py", line 265, in search
  File "build/bdist.linux-x86_64/egg/regex.py", line 496, in _compile
_regex_core.error: bad fuzzy cost limit at position 91
```

**Comment by Hoohm** [comment]
Hello @bishwaG 
Did you close this because you solved it?

**Comment by bishwaG** [comment]
Yes, I solved it. It was an user error.
