### ISSUE TITLE
error running cite-seq-count

### ISSUE THREAD

**Issue by fouerghi** [Hoohm/CITE-seq-Count#150]
Hi, 

I used to be able to use CITE-seq-Count 1.3 just fine, but I have tried to plug in results from a new experiment using python 3.7 and 3.8 and both times I got these errors:
Exception in thread Thread-3:
Traceback (most recent call last):

  File "/Users/opt/miniconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/opt/miniconda3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/opt/miniconda3/lib/python3.8/site-packages/multiprocess/pool.py", line 592, in _handle_results
    cache[job]._set(i, obj)
  File "/Users/opt/miniconda3/lib/python3.8/site-packages/multiprocess/pool.py", line 778, in _set
    self._error_callback(self._value)
TypeError: '_io.TextIOWrapper' object is not callable

**Comment by Hoohm** [comment]
I'm assuming it might be related to the way your paths are called.
Have you tried giving them directly as a harcoded path?

**Comment by fjrossello** [comment]
Hi,

Thanks for your prompt reply.
As advised, I tried using hardcoded paths in the script without success. 
I have also tried by including all necessary files within the same folder with the same outcome an error.

Find the script with hardcoded paths:

`CITE-seq-Count -R1 /homevol/frossello/projects/data/fastq/SC/HTO/clipped/S2_L001_R1_001.26bp_5prime.fq.gz \
        -R2 /homevol/frossello/projects/data/fastq/SC/HTO/clipped/S2_L001_R2_001.25bp_5prime.fq.gz \
        -t /homevol/frossello/projects/data/tables/tags.csv \
        -cbf 1 -cbl 16 -umif 17 -umil 26 --bc_collapsing_dist 0 --umi_collapsing_dist 1 --max-errors 1 --start-trim 10 -cells 0 -T 16 \
        -wl /homevol/frossello/projects/output/cite_seq_counts/barcodes.tsv \
        -o /homevol/frossello/projects/output/cite_seq_counts/sample_1`

Command when all files were included in the same folder:
`CITE-seq-Count -R1 S2_L001_R1_001.26bp_5prime.fq.gz -R2 S2_L001_R2_001.25bp_5prime.fq.gz -t tags.csv -cbf 1 -cbl 16 -umif 17 -umil 26 --bc_collapsing_dist 0 --umi_collapsing_dist 1 --max-errors 1 --start-trim 10 -cells 0 -T 32 -wl barcodes.tsv -o ./test/`

Thanks again for your help.

Cheers,

**Comment by Hoohm** [comment]
Doest it work if you call from he command line directly?

**Comment by fjrossello** [comment]
Hi,

Sorry, I am not sure what you mean by _from the command line directly_.

Thanks for your help. 

Cheers,

**Comment by Hoohm** [comment]
I'm assuming you are using a bash script to run CSC.
Could you try running it on a local computer, directly from the cmdline?
Only on a few reads, doesn't need to be all of them I guess.

**Comment by fjrossello** [comment]
Thanks for clarifying. I did run the last two examples re hardcoded paths from the command line. As I mentioned, still the same output.
Thanks again for your help.
Cheers,

**Comment by fjrossello** [comment]
An update. The origing of my issue was having a mixture of read lengths in `R2` (from `8` to `25` bases, `0.01% of the total no. od reads) which caused the error mentioned above.
Apologies for the hassle.
Cheers,
