### ISSUE TITLE
barcode bug

### ISSUE THREAD

**Issue by craigamartens** [Hoohm/CITE-seq-Count#152]
Hi, I have 2 issues, one is when setting the estimated cell number, CITE-seq-Count appears to force the cell count to that number.  I am worried this can lead to inaccurate/biased results.   For example, if I set cell number to 8000, I get 8000 +/- 10 cells back, if I set the same dataset to 10,000, I get ~10,000 back.  To try to avoid this, I tried to set the cell barcode mismatch to 0 and then got the following error.  

Correcting cell barcodes
Looking for a whitelist
Collapsing cell barcodes
Traceback (most recent call last):
  File "/home/martensc/.local/bin/CITE-seq-Count", line 11, in <module>
    load_entry_point('CITE-seq-Count==1.4.4', 'console_scripts', 'CITE-seq-Count')()
  File "/home/martensc/.local/lib/python3.6/site-packages/cite_seq_count/__main__.py", line 394, in main
    ab_map=ordered_tags_map)
  File "/home/martensc/.local/lib/python3.6/site-packages/cite_seq_count/processing.py", line 368, in correct_cells
    ab_map=ab_map,
  File "/home/martensc/.local/lib/python3.6/site-packages/cite_seq_count/processing.py", line 312, in collapse_cells
    for real_barcode in true_to_false:
TypeError: 'NoneType' object is not iterable

All I did was to add the following to my command, which works fine otherwise:  --bc_collapsing_dist 0
Thanks, Craig

**Comment by Hoohm** [comment]
Hello @craigamartens,

Thank you for pointing it out, I'll add it to my long list of fixes for 1.5.0 :)
