### ISSUE TITLE
Option "-u" not working in version 1.3.1

### ISSUE THREAD

**Issue by santiagorevale** [Hoohm/CITE-seq-Count#16]
Hi there,

I was trying the new option for printing the unknown tags, but it's giving me the following error:

```
[...]
Processed 1,000,000 lines in 7.649 secondes. Total lines processed: 27,000,000
Processed 1,000,000 lines in 7.69 secondes. Total lines processed: 28,000,000
Done counting
Traceback (most recent call last):
  File "~/miniconda3/envs/CITEseq-pipeline/bin/CITE-seq-Count", line 11, in <module>
    sys.exit(main())
  File "~/miniconda3/envs/CITEseq-pipeline/lib/python3.6/site-packages/cite_seq_count/__main__.py", line 350, in main
    no_match_matrix = pd.DataFrame(no_match_table.items(), columns=['tag', 'total'])
  File "~/miniconda3/envs/CITEseq-pipeline/lib/python3.6/site-packages/pandas/core/frame.py", line 422, in __init__
    raise ValueError('DataFrame constructor not properly called!')
ValueError: DataFrame constructor not properly called!
```

I'm not very proficiency at using *Pandas*, but I managed to make it work by replacing [the following line of code](https://github.com/Hoohm/CITE-seq-Count/blob/master/cite_seq_count/__main__.py#L350) for:

```python
keys = list(no_match_table.keys())
vals = list(no_match_table.values())
no_match_matrix = pd.DataFrame({"tag": keys, "total": vals})
```

I'm using the following versions:
- CITE-seq-Count v1.3.1
- Pandas v0.23.4
- Python v3.6.5

Best regards,
Santiago

**Comment by Hoohm** [comment]
Hello @santiagorevale  and thanks for the catch. I've changed it and tested it to your version. It's now pushed on git and pypi. You can upgrade to 1.3.2 using this: 
```
pip install CITE-seq-Count --no-cache-dir --upgrade
```
