### ISSUE TITLE
ValueError: columns cannot be a set

### ISSUE THREAD

**Issue by 77babyy** [Hoohm/CITE-seq-Count#192]
When I use "CITE-seq-Count-R1./ SRR13724311_S1_L001_R1_001.fastq.gz-R2 SRR13724311_S1_L001_R2_001.fastq.gz-t Cmca9_tag_list_utf8.cfa-cbf 1-cbl 16-umif 17-umil 28 -cells 10000-o OUTFOLDER "is always normal. Always normal when Looking for a whitelist, Correcting cell barcodes appear later
Looking for a whitelist
Collapsing cell barcodes
Correcting umis
Traceback (most recent call last):
File "/home/wangjiawen/miniconda3/bin/CITE-seq-Count", line 8, in <module>
sys.exit(main())
The File "/ home/wangjiawen/miniconda3 / lib/python3.9 / site - packages/cite_seq_count / __main__. Py", line 603, in the main
io.write_dense(
The File "/ home/wangjiawen/miniconda3 / lib/python3.9 / site - packages/cite_seq_count/IO. Py", 48, the line in write_dense
pandas_dense = pd.DataFrame(sparse_matrix.todense(), columns=columns, index=index)
The File "/ home/wangjiawen/miniconda3 / lib/python3.9 / site - packages/pandas/core/frame. Py", line 744, in __init__
raise ValueError("columns cannot be a set")
ValueError: columns cannot be a set, how do I solve this problem, this seems to be a python package error

**Comment by 77babyy** [comment]
Thanks a lot, I use pandas 1.4.0 to solve this problem.

**Comment by 77babyy** [comment]
My output file is 
"drwxr-xr-x 2    89 Apr 29 12:50 read_count
-rw-r--r-- 1   605 Apr 29 12:50 run_report.yaml
drwxr-xr-x 2    89 Apr 29 12:50 umi_count
drwxr-xr-x 2    36 Apr 29 12:50 uncorrected_cells
-rw-r--r-- 1 9711 Apr 29 12:50 unmapped.csv", the feature/barcode and matrix here are in R language, error occurs when reading 10x data“
> counts <- Read10X("/pool2/wangjiawen/fastq_2/SRR13724311/OUTFOLDER/read_count/")
Error in `[.data.frame`(feature.names, , gene.column) : 
  undefined columns selected
> counts <- Read10X("/pool2/wangjiawen/fastq_2/SRR13724311/OUTFOLDER/umi_count/")
Error in `[.data.frame`(feature.names, , gene.column) : 
  undefined columns selected”, what should I do？

**Comment by lemon-latte** [comment]
> My output file is "drwxr-xr-x 2 89 Apr 29 12:50 read_count -rw-r--r-- 1 605 Apr 29 12:50 run_report.yaml drwxr-xr-x 2 89 Apr 29 12:50 umi_count drwxr-xr-x 2 36 Apr 29 12:50 uncorrected_cells -rw-r--r-- 1 9711 Apr 29 12:50 unmapped.csv", the feature/barcode and matrix here are in R language, error occurs when reading 10x data“
> 
> > counts <- Read10X("/pool2/wangjiawen/fastq_2/SRR13724311/OUTFOLDER/read_count/")
> > Error in `[.data.frame`(feature.names, , gene.column) :
> > undefined columns selected
> > counts <- Read10X("/pool2/wangjiawen/fastq_2/SRR13724311/OUTFOLDER/umi_count/")
> > Error in `[.data.frame`(feature.names, , gene.column) :
> > undefined columns selected”, what should I do？
import data into R with following code:
counts <- Read10X("/pool2/wangjiawen/fastq_2/SRR13724311/OUTFOLDER/umi_count/",gene.column = 1)

**Comment by lemon-latte** [comment]
**import data into R by following code:
counts <- Read10X("/pool2/wangjiawen/fastq_2/SRR13724311/OUTFOLDER/umi_count/",gene.column = 1)**

> My output file is "drwxr-xr-x 2 89 Apr 29 12:50 read_count -rw-r--r-- 1 605 Apr 29 12:50 run_report.yaml drwxr-xr-x 2 89 Apr 29 12:50 umi_count drwxr-xr-x 2 36 Apr 29 12:50 uncorrected_cells -rw-r--r-- 1 9711 Apr 29 12:50 unmapped.csv", the feature/barcode and matrix here are in R language, error occurs when reading 10x data“
> 
> > counts <- Read10X("/pool2/wangjiawen/fastq_2/SRR13724311/OUTFOLDER/read_count/")
> > Error in `[.data.frame`(feature.names, , gene.column) :
> > undefined columns selected
> > counts <- Read10X("/pool2/wangjiawen/fastq_2/SRR13724311/OUTFOLDER/umi_count/")
> > Error in `[.data.frame`(feature.names, , gene.column) :
> > undefined columns selected”, what should I do？
