### ISSUE TITLE
IndexError: list index out of range when running CITE-Seq-Count

### ISSUE THREAD

**Issue by YunZheHuang** [Hoohm/CITE-seq-Count#63]
Hello,

I got this error when running the program:

`Traceback (most recent call last):
  File "/anaconda3/bin/CITE-seq-Count", line 11, in <module>
    sys.exit(main())
  File "/anaconda3/lib/python3.7/site-packages/cite_seq_count/__main__.py", line 245, in main
    ab_map = preprocessing.parse_tags_csv(args.tags)
  File "/anaconda3/lib/python3.7/site-packages/cite_seq_count/preprocessing.py", line 126, in parse_tags_csv
    tags[row[0].strip()] = row[1].strip()
IndexError: list index out of range
`
Can you please tell me how to fix it? Thank you !

**Comment by marencc** [comment]
Hi. Mine raised the same error. After reading other closed issues, I've solved it by deleting all empty lines/spaces in my "TAGs list" file. But, I read it could as well be an empty space in the "white list" of barcodes.
