### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by Sharks28** [Hoohm/CITE-seq-Count#7]
Hello,

I am running CITE-seq-count pipeline and it gives me UnboundLocalError.  Any suggestions?  Here is the code:

python /CITE-seq-Count-master/CITE-seq-count.py -R1 P-xxxx1.fastq.gz -R2 xxxx2.fastq.gz -t TAG_List.csv -cbf 1 -cbl 16 -umif 17 -umil 26 -tr "^[ATGC]{15}[TGC][A]{6,}" -hd 1 -o citeseqcount.tsv -cells 5000

Output: 

Traceback (most recent call last):
  File "/CITE-seq-Count-master/CITE-seq-count.py", line 232, in <module>
    main()
  File "/CITE-seq-Count-master/CITE-seq-count.py", line 151, in main
    tag_length = check_tags(ab_map, args.hamming_thresh)
  File "/CITE-seq-Count-master/CITE-seq-count.py", line 136, in check_tags
    return(len(a))
**UnboundLocalError: local variable 'a' referenced before assignment**

**Comment by Hoohm** [comment]
Yep, that is correct. Will be fixed in the next release.
