### ISSUE TITLE
struct.error: 'I' format requires 0 <= number <= 4294967295

### ISSUE THREAD

**Issue by AI1013** [Hoohm/CITE-seq-Count#75]
Hi all,

I have six R1 fastq.gz files and six R2 fastq.gz files, I merged them together separately, then used the following commands to run the cite-seq-count:
`CITE-seq-Count -R1 R1.fastq.gz -R2 R2.fastq.gz -t tags.csv -cbf 1 -cbl 16 -umif 17 -umil 26  -wl whitelist.txt -o ./ -cells 30000`
Everything goes well, except there is an error during the process:

> Process ForkPoolWorker-1:
Traceback (most recent call last):
  File "/ihome/crc/install/cite-seq-count/python3.7/lib/python3.7/site-packages/multiprocess/pool.py", line 127, in worker
    put((job, i, result))
  File "/ihome/crc/install/cite-seq-count/python3.7/lib/python3.7/site-packages/multiprocess/queues.py", line 367, in put
    self._writer.send_bytes(obj)
  File "/ihome/crc/install/cite-seq-count/python3.7/lib/python3.7/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/ihome/crc/install/cite-seq-count/python3.7/lib/python3.7/site-packages/multiprocess/connection.py", line 396, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/ihome/crc/install/cite-seq-count/python3.7/lib/python3.7/site-packages/multiprocess/process.py", line 297, in _bootstrap
    self.run()
  File "/ihome/crc/install/cite-seq-count/python3.7/lib/python3.7/site-packages/multiprocess/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/ihome/crc/install/cite-seq-count/python3.7/lib/python3.7/site-packages/multiprocess/pool.py", line 132, in worker
    put((job, i, (False, wrapped)))
  File "/ihome/crc/install/cite-seq-count/python3.7/lib/python3.7/site-packages/multiprocess/queues.py", line 361, in put
    obj = _ForkingPickler.dumps(obj)
  File "/ihome/crc/install/cite-seq-count/python3.7/lib/python3.7/site-packages/multiprocess/reduction.py", line 54, in dumps
    cls(buf, protocol).dump(obj)
  File "/ihome/crc/install/cite-seq-count/python3.7/lib/python3.7/pickle.py", line 437, in dump
    self.save(obj)
  File "/ihome/crc/install/cite-seq-count/python3.7/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/ihome/crc/install/cite-seq-count/python3.7/lib/python3.7/pickle.py", line 771, in save_tuple
    save(element)
  File "/ihome/crc/install/cite-seq-count/python3.7/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/ihome/crc/install/cite-seq-count/python3.7/lib/python3.7/pickle.py", line 771, in save_tuple
    save(element)
  File "/ihome/crc/install/cite-seq-count/python3.7/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/ihome/crc/install/cite-seq-count/python3.7/lib/python3.7/pickle.py", line 638, in save_reduce
    save(args)
  File "/ihome/crc/install/cite-seq-count/python3.7/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/ihome/crc/install/cite-seq-count/python3.7/lib/python3.7/pickle.py", line 771, in save_tuple
    save(element)
  File "/ihome/crc/install/cite-seq-count/python3.7/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/ihome/crc/install/cite-seq-count/python3.7/lib/python3.7/pickle.py", line 747, in save_str
    self._write_large_bytes(BINUNICODE + pack("<I", n), encoded)
struct.error: 'I' format requires 0 <= number <= 4294967295

I have no idea what happened, and the procedure is still running, not sure if this will influence the result. 

Would you please give me any suggestion on this?
Thank you!

**Comment by Hoohm** [comment]
Hello @AI1013 
How many reads are there in your files?

**Comment by AI1013** [comment]
Hi @Hoohm,
I just tried to run with each file separately, and it worked! I think it was because there were too many reads in the mixed file. Anyway, thank you!

**Comment by Hoohm** [comment]
Yes that's probably the issue. Happy to hear that it worked.

Closing this now.
