### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by hothri** [Hoohm/CITE-seq-Count#76]
Hi, 
I am getting below error while trying to run CiteSeq. What could be the reason for this error? 

Traceback (most recent call last):
  File "/CITE_seq_tool/cite_env/bin/CITE-seq-Count", line 10, in <module>
    sys.exit(main())
  File "/CITE_seq_tool/cite_env/lib/python3.6/site-packages/cite_seq_count/__main__.py", line 245, in main
    ab_map = preprocessing.parse_tags_csv(args.tags)
  File "/CITE_seq_tool/cite_env/lib/python3.6/site-packages/cite_seq_count/preprocessing.py", line 126, in parse_tags_csv
    tags[row[0].strip()] = row[1].strip()
IndexError: list index out of range

Thank you, 
Hothri

**Comment by myojencards** [comment]
I got this same error. I fixed it by deleting the empty line at the bottom of my cite/hash barcode list.

**Comment by hothri** [comment]
Thank you, its fixed
